Repository CS2113-AY1819S1-T13-1/main, pull requests merged in 2018-10, with the labels that each got.

#34 Update product names
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/core/Config.java
  src/test/java/seedu/address/commons/core/ConfigTest.java
Labels: misc

#39 [v1.2] Backup Feature
  src/main/java/seedu/address/commons/events/model/AddressBookLocalBackupEvent.java
  src/main/java/seedu/address/logic/commands/BackupCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/BackupCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/ui/UiManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/BackupCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/BackupCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
Labels: enhancement, p.High, status.InProgress, story.musthave

#56 Added UC10 to Developer Guide - Add Event Use Case
  docs/DeveloperGuide.adoc
Labels: priority.Medium, status.Complete, type.task

#61 improved on autocomplete and updated developer guide
  docs/DeveloperGuide.adoc
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/test/java/seedu/address/ui/CommandBoxTest.java
Labels: priority.High, status.InProgress, type.task

#62 [Documentation] Add documentation for backup feature
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/Ui.png
Labels: enhancement, priority.High, status.InProgress, type.task

#81 [Documentation] Edit UG,DG, add Portfolio
  docs/AboutUs.adoc
  docs/UserGuide.adoc
  docs/team/adrian.adoc
Labels: misc, priority.High, status.InProgress, type.task

#84 [Documentation/Feature] Backup and Restore feature
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  src/main/java/seedu/address/commons/events/model/BooksLocalBackupEvent.java
  src/main/java/seedu/address/commons/events/ui/NewNotificationAvailableEvent.java
  src/main/java/seedu/address/logic/commands/BackupCommand.java
  src/main/java/seedu/address/logic/commands/RestoreCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/storage/GitHubStorage.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/images/dialog-info.png
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: enhancement, misc, priority.High, status.InProgress, type.epic, type.task

#89 [v1.3] Fixes/ Tests/ Documentation for backup & restore feature
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/RestoreCommand.java
  src/main/java/seedu/address/logic/parser/RestoreCommandParser.java
  src/main/java/seedu/address/model/ExpenseBook.java
  src/main/java/seedu/address/storage/GithubStorage.java
  src/main/java/seedu/address/storage/JsonUserPrefsStorage.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/test/data/GithubStorageTest/ValidAddressBook.bak
  src/test/data/GithubStorageTest/ValidExpenseBook.bak
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/RestoreCommandTest.java
  src/test/java/seedu/address/logic/parser/RestoreCommandParserTest.java
  src/test/java/seedu/address/storage/GithubStorageTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
Labels: enhancement, misc, priority.High, status.Complete, story.musthave, type.epic, type.task

#94 Event Storage + Resolved checkstyle and merge conflicts
  _reposense/config.json
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/events/model/EventBookChangedEvent.java
  src/main/java/seedu/address/commons/events/model/EventBookLocalBackupEvent.java
  src/main/java/seedu/address/commons/events/model/EventBookLocalRestoreEvent.java
  src/main/java/seedu/address/commons/events/model/EventBookOnlineRestoreEvent.java
  src/main/java/seedu/address/logic/commands/AddEventCommand.java
  src/main/java/seedu/address/logic/commands/ClearEventCommand.java
  src/main/java/seedu/address/logic/commands/DeleteEventCommand.java
  src/main/java/seedu/address/model/EventBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyEventBook.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/VersionedEventBook.java
  src/main/java/seedu/address/model/event/Event.java
  src/main/java/seedu/address/model/event/EventList.java
  src/main/java/seedu/address/model/event/exceptions/EventNotFoundException.java
  src/main/java/seedu/address/model/eventContacts/EventContacts.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/EventBookStorage.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/storage/XmlAdaptedEvent.java
  src/main/java/seedu/address/storage/XmlAdaptedEventContact.java
  src/main/java/seedu/address/storage/XmlEventBookStorage.java
  src/main/java/seedu/address/storage/XmlFileStorage.java
  src/main/java/seedu/address/storage/XmlSerializableEventBook.java
  src/main/resources/view/EventListCard.fxml
  src/main/resources/view/EventListPanel.fxml
  src/test/java/seedu/address/TestApp.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddExpenseCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddExpenseCommandTest.java
  src/test/java/seedu/address/logic/commands/BackupCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearExpenseCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteExpenseCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditExpenseCommandTest.java
  src/test/java/seedu/address/logic/commands/FindAddressCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/FindNameCommandTest.java
  src/test/java/seedu/address/logic/commands/FindPhoneCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/commands/RedoCommandTest.java
  src/test/java/seedu/address/logic/commands/RedoExpenseCommandTest.java
  src/test/java/seedu/address/logic/commands/RestoreCommandTest.java
  src/test/java/seedu/address/logic/commands/SelectCommandTest.java
  src/test/java/seedu/address/logic/commands/UndoCommandTest.java
  src/test/java/seedu/address/logic/commands/UndoExpenseCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/EventBookBuilder.java
  src/test/java/seedu/address/testutil/EventBuilder.java
Labels: enhancement, priority.High, status.Complete, story.musthave, type.enhancement, type.epic, type.task

#96 [v1.3] Integrate all books into Backup & Restore Feature
  src/main/java/seedu/address/commons/events/model/TaskBookLocalBackupEvent.java
  src/main/java/seedu/address/commons/events/model/TaskBookLocalRestoreEvent.java
  src/main/java/seedu/address/commons/events/model/TaskBookOnlineRestoreEvent.java
  src/main/java/seedu/address/commons/events/storage/LocalBackupEvent.java
  src/main/java/seedu/address/commons/events/storage/LocalRestoreEvent.java
  src/main/java/seedu/address/commons/events/storage/OnlineBackupEvent.java
  src/main/java/seedu/address/logic/commands/BackupCommand.java
  src/main/java/seedu/address/logic/commands/RestoreCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddExpenseCommandTest.java
  src/test/java/seedu/address/logic/commands/RestoreCommandTest.java
  src/test/java/seedu/address/storage/GithubStorageTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
Labels: enhancement, priority.High, type.enhancement, type.story, type.task

#100 [Devops] Build.Gradle Changes
  build.gradle
Labels: enhancement
